#Config file for automatic testing at travis-ci.org

language: python
sudo: false

python:
   - 3.3
   - 3.4
   - 3.5

before_install:
   - pip install pytest-cov
   - pip install coveralls
   - python setup.py install

script:
   - py.test
   - py.test --cov tail

after_success:
- coveralls
